- id: shellcheck
  name: shellcheck
  language: system
  entry: shellcheck
  types: [shell]
- id: shfmt
  name: shfmt
  language: system
  entry: shfmt -i 0 -s -d
  types: [shell]
- id: flake518
  name: flake518
  language: system
  entry: flake518
  types: [python]
- id: vint
  name: vint
  language: system
  entry: vint -s
  types: [vim]
- id: prettier
  name: prettier
  language: system
  entry: prettier -w
  types_or: [yaml, css, scss]
- id: rome
  name: rome
  language: system
  entry: rome ci
  types_or: [javascript, ts, json]
- id: pylint
  name: pylint
  language: system
  entry: pylint
  types: [python]
- id: pytest
  name: pytest
  language: system
  entry: pytest
  types: [python]
  pass_filenames: false
- id: mypy
  name: mypy
  language: system
  entry: mypy
  types: [python]
  pass_filenames: false
- id: rubocop
  name: rubocop
  language: system
  types: [ruby]
  entry: rubocop -A
